# Generated by Django 4.0.2 on 2022-02-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registermodel',
            old_name='name',
            new_name='new_name',
        ),
    ]
